/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2raySubRouteImport } from './routes/v2ray-sub'
import { Route as V2rayShareRouteImport } from './routes/v2ray-share'
import { Route as UserManagerShareRouteImport } from './routes/user-manager-share'
import { Route as ShareRouteImport } from './routes/share'
import { Route as DnsShareRouteImport } from './routes/dns-share'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authLicenseActivationRouteImport } from './routes/(auth)/license-activation'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedXuiPanelsIndexRouteImport } from './routes/_authenticated/xui-panels/index'
import { Route as AuthenticatedV2rayPackagesIndexRouteImport } from './routes/_authenticated/v2ray-packages/index'
import { Route as AuthenticatedUserManagerIndexRouteImport } from './routes/_authenticated/user-manager/index'
import { Route as AuthenticatedTunnelHealthIndexRouteImport } from './routes/_authenticated/tunnel-health/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServersIndexRouteImport } from './routes/_authenticated/servers/index'
import { Route as AuthenticatedSecurityIndexRouteImport } from './routes/_authenticated/security/index'
import { Route as AuthenticatedResellersIndexRouteImport } from './routes/_authenticated/resellers/index'
import { Route as AuthenticatedResellerV2rayIndexRouteImport } from './routes/_authenticated/reseller-v2ray/index'
import { Route as AuthenticatedResellerUserManagerIndexRouteImport } from './routes/_authenticated/reseller-user-manager/index'
import { Route as AuthenticatedResellerPeersIndexRouteImport } from './routes/_authenticated/reseller-peers/index'
import { Route as AuthenticatedResellerDnsIndexRouteImport } from './routes/_authenticated/reseller-dns/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedPoolsIndexRouteImport } from './routes/_authenticated/pools/index'
import { Route as AuthenticatedPeersIndexRouteImport } from './routes/_authenticated/peers/index'
import { Route as AuthenticatedLogsIndexRouteImport } from './routes/_authenticated/logs/index'
import { Route as AuthenticatedInterfacesIndexRouteImport } from './routes/_authenticated/interfaces/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedFaoximaManagementIndexRouteImport } from './routes/_authenticated/faoxima-management/index'
import { Route as AuthenticatedDnsPlansIndexRouteImport } from './routes/_authenticated/dns-plans/index'
import { Route as AuthenticatedDnsPanelsIndexRouteImport } from './routes/_authenticated/dns-panels/index'
import { Route as AuthenticatedDnsAccountsIndexRouteImport } from './routes/_authenticated/dns-accounts/index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index'
import { Route as AuthenticatedApplicationPlansIndexRouteImport } from './routes/_authenticated/application-plans/index'
import { Route as AuthenticatedApplicationManagementIndexRouteImport } from './routes/_authenticated/application-management/index'
import { Route as AuthenticatedApplicationLocationsIndexRouteImport } from './routes/_authenticated/application-locations/index'
import { Route as AuthenticatedAccountingIndexRouteImport } from './routes/_authenticated/accounting/index'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings/system'
import { Route as AuthenticatedSettingsResellerBotRouteImport } from './routes/_authenticated/settings/reseller-bot'
import { Route as AuthenticatedSettingsLicenseRouteImport } from './routes/_authenticated/settings/license'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedBillingWalletRouteImport } from './routes/_authenticated/billing/wallet'
import { Route as AuthenticatedBillingV2rayTrafficPackagesRouteImport } from './routes/_authenticated/billing/v2ray-traffic-packages'
import { Route as AuthenticatedBillingUserManagerTrafficPackagesRouteImport } from './routes/_authenticated/billing/user-manager-traffic-packages'
import { Route as AuthenticatedBillingTrafficPackagesRouteImport } from './routes/_authenticated/billing/traffic-packages'
import { Route as AuthenticatedBillingInvoicesRouteImport } from './routes/_authenticated/billing/invoices'
import { Route as AuthenticatedResellersIdWalletRouteImport } from './routes/_authenticated/resellers/$id/wallet'
import { Route as AuthenticatedResellersIdBillingPricesRouteImport } from './routes/_authenticated/resellers/$id/billing-prices'

const V2raySubRoute = V2raySubRouteImport.update({
  id: '/v2ray-sub',
  path: '/v2ray-sub',
  getParentRoute: () => rootRouteImport,
} as any)
const V2rayShareRoute = V2rayShareRouteImport.update({
  id: '/v2ray-share',
  path: '/v2ray-share',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagerShareRoute = UserManagerShareRouteImport.update({
  id: '/user-manager-share',
  path: '/user-manager-share',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsShareRoute = DnsShareRouteImport.update({
  id: '/dns-share',
  path: '/dns-share',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authLicenseActivationRoute = authLicenseActivationRouteImport.update({
  id: '/(auth)/license-activation',
  path: '/license-activation',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedXuiPanelsIndexRoute =
  AuthenticatedXuiPanelsIndexRouteImport.update({
    id: '/xui-panels/',
    path: '/xui-panels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedV2rayPackagesIndexRoute =
  AuthenticatedV2rayPackagesIndexRouteImport.update({
    id: '/v2ray-packages/',
    path: '/v2ray-packages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserManagerIndexRoute =
  AuthenticatedUserManagerIndexRouteImport.update({
    id: '/user-manager/',
    path: '/user-manager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTunnelHealthIndexRoute =
  AuthenticatedTunnelHealthIndexRouteImport.update({
    id: '/tunnel-health/',
    path: '/tunnel-health/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedServersIndexRoute =
  AuthenticatedServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecurityIndexRoute =
  AuthenticatedSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellersIndexRoute =
  AuthenticatedResellersIndexRouteImport.update({
    id: '/resellers/',
    path: '/resellers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellerV2rayIndexRoute =
  AuthenticatedResellerV2rayIndexRouteImport.update({
    id: '/reseller-v2ray/',
    path: '/reseller-v2ray/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellerUserManagerIndexRoute =
  AuthenticatedResellerUserManagerIndexRouteImport.update({
    id: '/reseller-user-manager/',
    path: '/reseller-user-manager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellerPeersIndexRoute =
  AuthenticatedResellerPeersIndexRouteImport.update({
    id: '/reseller-peers/',
    path: '/reseller-peers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellerDnsIndexRoute =
  AuthenticatedResellerDnsIndexRouteImport.update({
    id: '/reseller-dns/',
    path: '/reseller-dns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoolsIndexRoute = AuthenticatedPoolsIndexRouteImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeersIndexRoute = AuthenticatedPeersIndexRouteImport.update({
  id: '/peers/',
  path: '/peers/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsIndexRoute = AuthenticatedLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterfacesIndexRoute =
  AuthenticatedInterfacesIndexRouteImport.update({
    id: '/interfaces/',
    path: '/interfaces/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaoximaManagementIndexRoute =
  AuthenticatedFaoximaManagementIndexRouteImport.update({
    id: '/faoxima-management/',
    path: '/faoxima-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDnsPlansIndexRoute =
  AuthenticatedDnsPlansIndexRouteImport.update({
    id: '/dns-plans/',
    path: '/dns-plans/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDnsPanelsIndexRoute =
  AuthenticatedDnsPanelsIndexRouteImport.update({
    id: '/dns-panels/',
    path: '/dns-panels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDnsAccountsIndexRoute =
  AuthenticatedDnsAccountsIndexRouteImport.update({
    id: '/dns-accounts/',
    path: '/dns-accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationPlansIndexRoute =
  AuthenticatedApplicationPlansIndexRouteImport.update({
    id: '/application-plans/',
    path: '/application-plans/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationManagementIndexRoute =
  AuthenticatedApplicationManagementIndexRouteImport.update({
    id: '/application-management/',
    path: '/application-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationLocationsIndexRoute =
  AuthenticatedApplicationLocationsIndexRouteImport.update({
    id: '/application-locations/',
    path: '/application-locations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingIndexRoute =
  AuthenticatedAccountingIndexRouteImport.update({
    id: '/accounting/',
    path: '/accounting/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsResellerBotRoute =
  AuthenticatedSettingsResellerBotRouteImport.update({
    id: '/reseller-bot',
    path: '/reseller-bot',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsLicenseRoute =
  AuthenticatedSettingsLicenseRouteImport.update({
    id: '/license',
    path: '/license',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedBillingWalletRoute =
  AuthenticatedBillingWalletRouteImport.update({
    id: '/billing/wallet',
    path: '/billing/wallet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingV2rayTrafficPackagesRoute =
  AuthenticatedBillingV2rayTrafficPackagesRouteImport.update({
    id: '/billing/v2ray-traffic-packages',
    path: '/billing/v2ray-traffic-packages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingUserManagerTrafficPackagesRoute =
  AuthenticatedBillingUserManagerTrafficPackagesRouteImport.update({
    id: '/billing/user-manager-traffic-packages',
    path: '/billing/user-manager-traffic-packages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingTrafficPackagesRoute =
  AuthenticatedBillingTrafficPackagesRouteImport.update({
    id: '/billing/traffic-packages',
    path: '/billing/traffic-packages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingInvoicesRoute =
  AuthenticatedBillingInvoicesRouteImport.update({
    id: '/billing/invoices',
    path: '/billing/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellersIdWalletRoute =
  AuthenticatedResellersIdWalletRouteImport.update({
    id: '/resellers/$id/wallet',
    path: '/resellers/$id/wallet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellersIdBillingPricesRoute =
  AuthenticatedResellersIdBillingPricesRouteImport.update({
    id: '/resellers/$id/billing-prices',
    path: '/resellers/$id/billing-prices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/dns-share': typeof DnsShareRoute
  '/share': typeof ShareRoute
  '/user-manager-share': typeof UserManagerShareRoute
  '/v2ray-share': typeof V2rayShareRoute
  '/v2ray-sub': typeof V2raySubRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/license-activation': typeof authLicenseActivationRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/billing/invoices': typeof AuthenticatedBillingInvoicesRoute
  '/billing/traffic-packages': typeof AuthenticatedBillingTrafficPackagesRoute
  '/billing/user-manager-traffic-packages': typeof AuthenticatedBillingUserManagerTrafficPackagesRoute
  '/billing/v2ray-traffic-packages': typeof AuthenticatedBillingV2rayTrafficPackagesRoute
  '/billing/wallet': typeof AuthenticatedBillingWalletRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/license': typeof AuthenticatedSettingsLicenseRoute
  '/settings/reseller-bot': typeof AuthenticatedSettingsResellerBotRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/application-locations/': typeof AuthenticatedApplicationLocationsIndexRoute
  '/application-management/': typeof AuthenticatedApplicationManagementIndexRoute
  '/application-plans/': typeof AuthenticatedApplicationPlansIndexRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/dns-accounts/': typeof AuthenticatedDnsAccountsIndexRoute
  '/dns-panels/': typeof AuthenticatedDnsPanelsIndexRoute
  '/dns-plans/': typeof AuthenticatedDnsPlansIndexRoute
  '/faoxima-management/': typeof AuthenticatedFaoximaManagementIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/interfaces/': typeof AuthenticatedInterfacesIndexRoute
  '/logs/': typeof AuthenticatedLogsIndexRoute
  '/peers/': typeof AuthenticatedPeersIndexRoute
  '/pools/': typeof AuthenticatedPoolsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/reseller-dns/': typeof AuthenticatedResellerDnsIndexRoute
  '/reseller-peers/': typeof AuthenticatedResellerPeersIndexRoute
  '/reseller-user-manager/': typeof AuthenticatedResellerUserManagerIndexRoute
  '/reseller-v2ray/': typeof AuthenticatedResellerV2rayIndexRoute
  '/resellers/': typeof AuthenticatedResellersIndexRoute
  '/security/': typeof AuthenticatedSecurityIndexRoute
  '/servers/': typeof AuthenticatedServersIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tunnel-health/': typeof AuthenticatedTunnelHealthIndexRoute
  '/user-manager/': typeof AuthenticatedUserManagerIndexRoute
  '/v2ray-packages/': typeof AuthenticatedV2rayPackagesIndexRoute
  '/xui-panels/': typeof AuthenticatedXuiPanelsIndexRoute
  '/resellers/$id/billing-prices': typeof AuthenticatedResellersIdBillingPricesRoute
  '/resellers/$id/wallet': typeof AuthenticatedResellersIdWalletRoute
}
export interface FileRoutesByTo {
  '/dns-share': typeof DnsShareRoute
  '/share': typeof ShareRoute
  '/user-manager-share': typeof UserManagerShareRoute
  '/v2ray-share': typeof V2rayShareRoute
  '/v2ray-sub': typeof V2raySubRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/license-activation': typeof authLicenseActivationRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/billing/invoices': typeof AuthenticatedBillingInvoicesRoute
  '/billing/traffic-packages': typeof AuthenticatedBillingTrafficPackagesRoute
  '/billing/user-manager-traffic-packages': typeof AuthenticatedBillingUserManagerTrafficPackagesRoute
  '/billing/v2ray-traffic-packages': typeof AuthenticatedBillingV2rayTrafficPackagesRoute
  '/billing/wallet': typeof AuthenticatedBillingWalletRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/license': typeof AuthenticatedSettingsLicenseRoute
  '/settings/reseller-bot': typeof AuthenticatedSettingsResellerBotRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/accounting': typeof AuthenticatedAccountingIndexRoute
  '/application-locations': typeof AuthenticatedApplicationLocationsIndexRoute
  '/application-management': typeof AuthenticatedApplicationManagementIndexRoute
  '/application-plans': typeof AuthenticatedApplicationPlansIndexRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/dns-accounts': typeof AuthenticatedDnsAccountsIndexRoute
  '/dns-panels': typeof AuthenticatedDnsPanelsIndexRoute
  '/dns-plans': typeof AuthenticatedDnsPlansIndexRoute
  '/faoxima-management': typeof AuthenticatedFaoximaManagementIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/interfaces': typeof AuthenticatedInterfacesIndexRoute
  '/logs': typeof AuthenticatedLogsIndexRoute
  '/peers': typeof AuthenticatedPeersIndexRoute
  '/pools': typeof AuthenticatedPoolsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/reseller-dns': typeof AuthenticatedResellerDnsIndexRoute
  '/reseller-peers': typeof AuthenticatedResellerPeersIndexRoute
  '/reseller-user-manager': typeof AuthenticatedResellerUserManagerIndexRoute
  '/reseller-v2ray': typeof AuthenticatedResellerV2rayIndexRoute
  '/resellers': typeof AuthenticatedResellersIndexRoute
  '/security': typeof AuthenticatedSecurityIndexRoute
  '/servers': typeof AuthenticatedServersIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tunnel-health': typeof AuthenticatedTunnelHealthIndexRoute
  '/user-manager': typeof AuthenticatedUserManagerIndexRoute
  '/v2ray-packages': typeof AuthenticatedV2rayPackagesIndexRoute
  '/xui-panels': typeof AuthenticatedXuiPanelsIndexRoute
  '/resellers/$id/billing-prices': typeof AuthenticatedResellersIdBillingPricesRoute
  '/resellers/$id/wallet': typeof AuthenticatedResellersIdWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/dns-share': typeof DnsShareRoute
  '/share': typeof ShareRoute
  '/user-manager-share': typeof UserManagerShareRoute
  '/v2ray-share': typeof V2rayShareRoute
  '/v2ray-sub': typeof V2raySubRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/license-activation': typeof authLicenseActivationRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/billing/invoices': typeof AuthenticatedBillingInvoicesRoute
  '/_authenticated/billing/traffic-packages': typeof AuthenticatedBillingTrafficPackagesRoute
  '/_authenticated/billing/user-manager-traffic-packages': typeof AuthenticatedBillingUserManagerTrafficPackagesRoute
  '/_authenticated/billing/v2ray-traffic-packages': typeof AuthenticatedBillingV2rayTrafficPackagesRoute
  '/_authenticated/billing/wallet': typeof AuthenticatedBillingWalletRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/license': typeof AuthenticatedSettingsLicenseRoute
  '/_authenticated/settings/reseller-bot': typeof AuthenticatedSettingsResellerBotRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/_authenticated/application-locations/': typeof AuthenticatedApplicationLocationsIndexRoute
  '/_authenticated/application-management/': typeof AuthenticatedApplicationManagementIndexRoute
  '/_authenticated/application-plans/': typeof AuthenticatedApplicationPlansIndexRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/dns-accounts/': typeof AuthenticatedDnsAccountsIndexRoute
  '/_authenticated/dns-panels/': typeof AuthenticatedDnsPanelsIndexRoute
  '/_authenticated/dns-plans/': typeof AuthenticatedDnsPlansIndexRoute
  '/_authenticated/faoxima-management/': typeof AuthenticatedFaoximaManagementIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/interfaces/': typeof AuthenticatedInterfacesIndexRoute
  '/_authenticated/logs/': typeof AuthenticatedLogsIndexRoute
  '/_authenticated/peers/': typeof AuthenticatedPeersIndexRoute
  '/_authenticated/pools/': typeof AuthenticatedPoolsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/reseller-dns/': typeof AuthenticatedResellerDnsIndexRoute
  '/_authenticated/reseller-peers/': typeof AuthenticatedResellerPeersIndexRoute
  '/_authenticated/reseller-user-manager/': typeof AuthenticatedResellerUserManagerIndexRoute
  '/_authenticated/reseller-v2ray/': typeof AuthenticatedResellerV2rayIndexRoute
  '/_authenticated/resellers/': typeof AuthenticatedResellersIndexRoute
  '/_authenticated/security/': typeof AuthenticatedSecurityIndexRoute
  '/_authenticated/servers/': typeof AuthenticatedServersIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tunnel-health/': typeof AuthenticatedTunnelHealthIndexRoute
  '/_authenticated/user-manager/': typeof AuthenticatedUserManagerIndexRoute
  '/_authenticated/v2ray-packages/': typeof AuthenticatedV2rayPackagesIndexRoute
  '/_authenticated/xui-panels/': typeof AuthenticatedXuiPanelsIndexRoute
  '/_authenticated/resellers/$id/billing-prices': typeof AuthenticatedResellersIdBillingPricesRoute
  '/_authenticated/resellers/$id/wallet': typeof AuthenticatedResellersIdWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dns-share'
    | '/share'
    | '/user-manager-share'
    | '/v2ray-share'
    | '/v2ray-sub'
    | '/settings'
    | '/forgot-password'
    | '/license-activation'
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/billing/invoices'
    | '/billing/traffic-packages'
    | '/billing/user-manager-traffic-packages'
    | '/billing/v2ray-traffic-packages'
    | '/billing/wallet'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/license'
    | '/settings/reseller-bot'
    | '/settings/system'
    | '/accounting/'
    | '/application-locations/'
    | '/application-management/'
    | '/application-plans/'
    | '/applications/'
    | '/dns-accounts/'
    | '/dns-panels/'
    | '/dns-plans/'
    | '/faoxima-management/'
    | '/help-center/'
    | '/interfaces/'
    | '/logs/'
    | '/peers/'
    | '/pools/'
    | '/reports/'
    | '/reseller-dns/'
    | '/reseller-peers/'
    | '/reseller-user-manager/'
    | '/reseller-v2ray/'
    | '/resellers/'
    | '/security/'
    | '/servers/'
    | '/settings/'
    | '/tunnel-health/'
    | '/user-manager/'
    | '/v2ray-packages/'
    | '/xui-panels/'
    | '/resellers/$id/billing-prices'
    | '/resellers/$id/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dns-share'
    | '/share'
    | '/user-manager-share'
    | '/v2ray-share'
    | '/v2ray-sub'
    | '/forgot-password'
    | '/license-activation'
    | '/otp'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/billing/invoices'
    | '/billing/traffic-packages'
    | '/billing/user-manager-traffic-packages'
    | '/billing/v2ray-traffic-packages'
    | '/billing/wallet'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/license'
    | '/settings/reseller-bot'
    | '/settings/system'
    | '/accounting'
    | '/application-locations'
    | '/application-management'
    | '/application-plans'
    | '/applications'
    | '/dns-accounts'
    | '/dns-panels'
    | '/dns-plans'
    | '/faoxima-management'
    | '/help-center'
    | '/interfaces'
    | '/logs'
    | '/peers'
    | '/pools'
    | '/reports'
    | '/reseller-dns'
    | '/reseller-peers'
    | '/reseller-user-manager'
    | '/reseller-v2ray'
    | '/resellers'
    | '/security'
    | '/servers'
    | '/settings'
    | '/tunnel-health'
    | '/user-manager'
    | '/v2ray-packages'
    | '/xui-panels'
    | '/resellers/$id/billing-prices'
    | '/resellers/$id/wallet'
  id:
    | '__root__'
    | '/_authenticated'
    | '/dns-share'
    | '/share'
    | '/user-manager-share'
    | '/v2ray-share'
    | '/v2ray-sub'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/license-activation'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/billing/invoices'
    | '/_authenticated/billing/traffic-packages'
    | '/_authenticated/billing/user-manager-traffic-packages'
    | '/_authenticated/billing/v2ray-traffic-packages'
    | '/_authenticated/billing/wallet'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/license'
    | '/_authenticated/settings/reseller-bot'
    | '/_authenticated/settings/system'
    | '/_authenticated/accounting/'
    | '/_authenticated/application-locations/'
    | '/_authenticated/application-management/'
    | '/_authenticated/application-plans/'
    | '/_authenticated/applications/'
    | '/_authenticated/dns-accounts/'
    | '/_authenticated/dns-panels/'
    | '/_authenticated/dns-plans/'
    | '/_authenticated/faoxima-management/'
    | '/_authenticated/help-center/'
    | '/_authenticated/interfaces/'
    | '/_authenticated/logs/'
    | '/_authenticated/peers/'
    | '/_authenticated/pools/'
    | '/_authenticated/reports/'
    | '/_authenticated/reseller-dns/'
    | '/_authenticated/reseller-peers/'
    | '/_authenticated/reseller-user-manager/'
    | '/_authenticated/reseller-v2ray/'
    | '/_authenticated/resellers/'
    | '/_authenticated/security/'
    | '/_authenticated/servers/'
    | '/_authenticated/settings/'
    | '/_authenticated/tunnel-health/'
    | '/_authenticated/user-manager/'
    | '/_authenticated/v2ray-packages/'
    | '/_authenticated/xui-panels/'
    | '/_authenticated/resellers/$id/billing-prices'
    | '/_authenticated/resellers/$id/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DnsShareRoute: typeof DnsShareRoute
  ShareRoute: typeof ShareRoute
  UserManagerShareRoute: typeof UserManagerShareRoute
  V2rayShareRoute: typeof V2rayShareRoute
  V2raySubRoute: typeof V2raySubRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLicenseActivationRoute: typeof authLicenseActivationRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2ray-sub': {
      id: '/v2ray-sub'
      path: '/v2ray-sub'
      fullPath: '/v2ray-sub'
      preLoaderRoute: typeof V2raySubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2ray-share': {
      id: '/v2ray-share'
      path: '/v2ray-share'
      fullPath: '/v2ray-share'
      preLoaderRoute: typeof V2rayShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-manager-share': {
      id: '/user-manager-share'
      path: '/user-manager-share'
      fullPath: '/user-manager-share'
      preLoaderRoute: typeof UserManagerShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns-share': {
      id: '/dns-share'
      path: '/dns-share'
      fullPath: '/dns-share'
      preLoaderRoute: typeof DnsShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/license-activation': {
      id: '/(auth)/license-activation'
      path: '/license-activation'
      fullPath: '/license-activation'
      preLoaderRoute: typeof authLicenseActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/xui-panels/': {
      id: '/_authenticated/xui-panels/'
      path: '/xui-panels'
      fullPath: '/xui-panels/'
      preLoaderRoute: typeof AuthenticatedXuiPanelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/v2ray-packages/': {
      id: '/_authenticated/v2ray-packages/'
      path: '/v2ray-packages'
      fullPath: '/v2ray-packages/'
      preLoaderRoute: typeof AuthenticatedV2rayPackagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-manager/': {
      id: '/_authenticated/user-manager/'
      path: '/user-manager'
      fullPath: '/user-manager/'
      preLoaderRoute: typeof AuthenticatedUserManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tunnel-health/': {
      id: '/_authenticated/tunnel-health/'
      path: '/tunnel-health'
      fullPath: '/tunnel-health/'
      preLoaderRoute: typeof AuthenticatedTunnelHealthIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/servers/': {
      id: '/_authenticated/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthenticatedServersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/': {
      id: '/_authenticated/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof AuthenticatedSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resellers/': {
      id: '/_authenticated/resellers/'
      path: '/resellers'
      fullPath: '/resellers/'
      preLoaderRoute: typeof AuthenticatedResellersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reseller-v2ray/': {
      id: '/_authenticated/reseller-v2ray/'
      path: '/reseller-v2ray'
      fullPath: '/reseller-v2ray/'
      preLoaderRoute: typeof AuthenticatedResellerV2rayIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reseller-user-manager/': {
      id: '/_authenticated/reseller-user-manager/'
      path: '/reseller-user-manager'
      fullPath: '/reseller-user-manager/'
      preLoaderRoute: typeof AuthenticatedResellerUserManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reseller-peers/': {
      id: '/_authenticated/reseller-peers/'
      path: '/reseller-peers'
      fullPath: '/reseller-peers/'
      preLoaderRoute: typeof AuthenticatedResellerPeersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reseller-dns/': {
      id: '/_authenticated/reseller-dns/'
      path: '/reseller-dns'
      fullPath: '/reseller-dns/'
      preLoaderRoute: typeof AuthenticatedResellerDnsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pools/': {
      id: '/_authenticated/pools/'
      path: '/pools'
      fullPath: '/pools/'
      preLoaderRoute: typeof AuthenticatedPoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/peers/': {
      id: '/_authenticated/peers/'
      path: '/peers'
      fullPath: '/peers/'
      preLoaderRoute: typeof AuthenticatedPeersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs/': {
      id: '/_authenticated/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthenticatedLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interfaces/': {
      id: '/_authenticated/interfaces/'
      path: '/interfaces'
      fullPath: '/interfaces/'
      preLoaderRoute: typeof AuthenticatedInterfacesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faoxima-management/': {
      id: '/_authenticated/faoxima-management/'
      path: '/faoxima-management'
      fullPath: '/faoxima-management/'
      preLoaderRoute: typeof AuthenticatedFaoximaManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dns-plans/': {
      id: '/_authenticated/dns-plans/'
      path: '/dns-plans'
      fullPath: '/dns-plans/'
      preLoaderRoute: typeof AuthenticatedDnsPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dns-panels/': {
      id: '/_authenticated/dns-panels/'
      path: '/dns-panels'
      fullPath: '/dns-panels/'
      preLoaderRoute: typeof AuthenticatedDnsPanelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dns-accounts/': {
      id: '/_authenticated/dns-accounts/'
      path: '/dns-accounts'
      fullPath: '/dns-accounts/'
      preLoaderRoute: typeof AuthenticatedDnsAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/application-plans/': {
      id: '/_authenticated/application-plans/'
      path: '/application-plans'
      fullPath: '/application-plans/'
      preLoaderRoute: typeof AuthenticatedApplicationPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/application-management/': {
      id: '/_authenticated/application-management/'
      path: '/application-management'
      fullPath: '/application-management/'
      preLoaderRoute: typeof AuthenticatedApplicationManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/application-locations/': {
      id: '/_authenticated/application-locations/'
      path: '/application-locations'
      fullPath: '/application-locations/'
      preLoaderRoute: typeof AuthenticatedApplicationLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/': {
      id: '/_authenticated/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AuthenticatedAccountingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/reseller-bot': {
      id: '/_authenticated/settings/reseller-bot'
      path: '/reseller-bot'
      fullPath: '/settings/reseller-bot'
      preLoaderRoute: typeof AuthenticatedSettingsResellerBotRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/license': {
      id: '/_authenticated/settings/license'
      path: '/license'
      fullPath: '/settings/license'
      preLoaderRoute: typeof AuthenticatedSettingsLicenseRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/billing/wallet': {
      id: '/_authenticated/billing/wallet'
      path: '/billing/wallet'
      fullPath: '/billing/wallet'
      preLoaderRoute: typeof AuthenticatedBillingWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/v2ray-traffic-packages': {
      id: '/_authenticated/billing/v2ray-traffic-packages'
      path: '/billing/v2ray-traffic-packages'
      fullPath: '/billing/v2ray-traffic-packages'
      preLoaderRoute: typeof AuthenticatedBillingV2rayTrafficPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/user-manager-traffic-packages': {
      id: '/_authenticated/billing/user-manager-traffic-packages'
      path: '/billing/user-manager-traffic-packages'
      fullPath: '/billing/user-manager-traffic-packages'
      preLoaderRoute: typeof AuthenticatedBillingUserManagerTrafficPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/traffic-packages': {
      id: '/_authenticated/billing/traffic-packages'
      path: '/billing/traffic-packages'
      fullPath: '/billing/traffic-packages'
      preLoaderRoute: typeof AuthenticatedBillingTrafficPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/invoices': {
      id: '/_authenticated/billing/invoices'
      path: '/billing/invoices'
      fullPath: '/billing/invoices'
      preLoaderRoute: typeof AuthenticatedBillingInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resellers/$id/wallet': {
      id: '/_authenticated/resellers/$id/wallet'
      path: '/resellers/$id/wallet'
      fullPath: '/resellers/$id/wallet'
      preLoaderRoute: typeof AuthenticatedResellersIdWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resellers/$id/billing-prices': {
      id: '/_authenticated/resellers/$id/billing-prices'
      path: '/resellers/$id/billing-prices'
      fullPath: '/resellers/$id/billing-prices'
      preLoaderRoute: typeof AuthenticatedResellersIdBillingPricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsLicenseRoute: typeof AuthenticatedSettingsLicenseRoute
  AuthenticatedSettingsResellerBotRoute: typeof AuthenticatedSettingsResellerBotRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsLicenseRoute: AuthenticatedSettingsLicenseRoute,
    AuthenticatedSettingsResellerBotRoute:
      AuthenticatedSettingsResellerBotRoute,
    AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBillingInvoicesRoute: typeof AuthenticatedBillingInvoicesRoute
  AuthenticatedBillingTrafficPackagesRoute: typeof AuthenticatedBillingTrafficPackagesRoute
  AuthenticatedBillingUserManagerTrafficPackagesRoute: typeof AuthenticatedBillingUserManagerTrafficPackagesRoute
  AuthenticatedBillingV2rayTrafficPackagesRoute: typeof AuthenticatedBillingV2rayTrafficPackagesRoute
  AuthenticatedBillingWalletRoute: typeof AuthenticatedBillingWalletRoute
  AuthenticatedAccountingIndexRoute: typeof AuthenticatedAccountingIndexRoute
  AuthenticatedApplicationLocationsIndexRoute: typeof AuthenticatedApplicationLocationsIndexRoute
  AuthenticatedApplicationManagementIndexRoute: typeof AuthenticatedApplicationManagementIndexRoute
  AuthenticatedApplicationPlansIndexRoute: typeof AuthenticatedApplicationPlansIndexRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
  AuthenticatedDnsAccountsIndexRoute: typeof AuthenticatedDnsAccountsIndexRoute
  AuthenticatedDnsPanelsIndexRoute: typeof AuthenticatedDnsPanelsIndexRoute
  AuthenticatedDnsPlansIndexRoute: typeof AuthenticatedDnsPlansIndexRoute
  AuthenticatedFaoximaManagementIndexRoute: typeof AuthenticatedFaoximaManagementIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedInterfacesIndexRoute: typeof AuthenticatedInterfacesIndexRoute
  AuthenticatedLogsIndexRoute: typeof AuthenticatedLogsIndexRoute
  AuthenticatedPeersIndexRoute: typeof AuthenticatedPeersIndexRoute
  AuthenticatedPoolsIndexRoute: typeof AuthenticatedPoolsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedResellerDnsIndexRoute: typeof AuthenticatedResellerDnsIndexRoute
  AuthenticatedResellerPeersIndexRoute: typeof AuthenticatedResellerPeersIndexRoute
  AuthenticatedResellerUserManagerIndexRoute: typeof AuthenticatedResellerUserManagerIndexRoute
  AuthenticatedResellerV2rayIndexRoute: typeof AuthenticatedResellerV2rayIndexRoute
  AuthenticatedResellersIndexRoute: typeof AuthenticatedResellersIndexRoute
  AuthenticatedSecurityIndexRoute: typeof AuthenticatedSecurityIndexRoute
  AuthenticatedServersIndexRoute: typeof AuthenticatedServersIndexRoute
  AuthenticatedTunnelHealthIndexRoute: typeof AuthenticatedTunnelHealthIndexRoute
  AuthenticatedUserManagerIndexRoute: typeof AuthenticatedUserManagerIndexRoute
  AuthenticatedV2rayPackagesIndexRoute: typeof AuthenticatedV2rayPackagesIndexRoute
  AuthenticatedXuiPanelsIndexRoute: typeof AuthenticatedXuiPanelsIndexRoute
  AuthenticatedResellersIdBillingPricesRoute: typeof AuthenticatedResellersIdBillingPricesRoute
  AuthenticatedResellersIdWalletRoute: typeof AuthenticatedResellersIdWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBillingInvoicesRoute: AuthenticatedBillingInvoicesRoute,
  AuthenticatedBillingTrafficPackagesRoute:
    AuthenticatedBillingTrafficPackagesRoute,
  AuthenticatedBillingUserManagerTrafficPackagesRoute:
    AuthenticatedBillingUserManagerTrafficPackagesRoute,
  AuthenticatedBillingV2rayTrafficPackagesRoute:
    AuthenticatedBillingV2rayTrafficPackagesRoute,
  AuthenticatedBillingWalletRoute: AuthenticatedBillingWalletRoute,
  AuthenticatedAccountingIndexRoute: AuthenticatedAccountingIndexRoute,
  AuthenticatedApplicationLocationsIndexRoute:
    AuthenticatedApplicationLocationsIndexRoute,
  AuthenticatedApplicationManagementIndexRoute:
    AuthenticatedApplicationManagementIndexRoute,
  AuthenticatedApplicationPlansIndexRoute:
    AuthenticatedApplicationPlansIndexRoute,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedDnsAccountsIndexRoute: AuthenticatedDnsAccountsIndexRoute,
  AuthenticatedDnsPanelsIndexRoute: AuthenticatedDnsPanelsIndexRoute,
  AuthenticatedDnsPlansIndexRoute: AuthenticatedDnsPlansIndexRoute,
  AuthenticatedFaoximaManagementIndexRoute:
    AuthenticatedFaoximaManagementIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedInterfacesIndexRoute: AuthenticatedInterfacesIndexRoute,
  AuthenticatedLogsIndexRoute: AuthenticatedLogsIndexRoute,
  AuthenticatedPeersIndexRoute: AuthenticatedPeersIndexRoute,
  AuthenticatedPoolsIndexRoute: AuthenticatedPoolsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedResellerDnsIndexRoute: AuthenticatedResellerDnsIndexRoute,
  AuthenticatedResellerPeersIndexRoute: AuthenticatedResellerPeersIndexRoute,
  AuthenticatedResellerUserManagerIndexRoute:
    AuthenticatedResellerUserManagerIndexRoute,
  AuthenticatedResellerV2rayIndexRoute: AuthenticatedResellerV2rayIndexRoute,
  AuthenticatedResellersIndexRoute: AuthenticatedResellersIndexRoute,
  AuthenticatedSecurityIndexRoute: AuthenticatedSecurityIndexRoute,
  AuthenticatedServersIndexRoute: AuthenticatedServersIndexRoute,
  AuthenticatedTunnelHealthIndexRoute: AuthenticatedTunnelHealthIndexRoute,
  AuthenticatedUserManagerIndexRoute: AuthenticatedUserManagerIndexRoute,
  AuthenticatedV2rayPackagesIndexRoute: AuthenticatedV2rayPackagesIndexRoute,
  AuthenticatedXuiPanelsIndexRoute: AuthenticatedXuiPanelsIndexRoute,
  AuthenticatedResellersIdBillingPricesRoute:
    AuthenticatedResellersIdBillingPricesRoute,
  AuthenticatedResellersIdWalletRoute: AuthenticatedResellersIdWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DnsShareRoute: DnsShareRoute,
  ShareRoute: ShareRoute,
  UserManagerShareRoute: UserManagerShareRoute,
  V2rayShareRoute: V2rayShareRoute,
  V2raySubRoute: V2raySubRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLicenseActivationRoute: authLicenseActivationRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
